Repository byteskeptical/sftpretty, pull requests merged in 2022-09, with the labels that each got.

#10 Flat Tire
  .github/workflows/test.yml
  README.rst
  docs/index.rst
  setup.py
  sftpretty/__init__.py
  sftpretty/helpers.py
Labels: bug

#12 Add ability to disable certain algorithms
  README.rst
  docs/authors.rst
  docs/changes.rst
  docs/cookbook.rst
  docs/index.rst
  docs/sftpretty.rst
  setup.py
  sftpretty/__init__.py
Labels: enhancement

#13 Open Windows
  README.rst
  docs/authors.rst
  docs/changes.rst
  docs/conf.py
  setup.py
  sftpretty/__init__.py
  sftpretty/helpers.py
Labels: bug, enhancement
